version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- win32
- x64

init:
- ps: >-
    $date = Get-Date

    $year = $date.ToString("yy")

    $build = $year + "{0:D3}" -f $date.DayOfYear

    $version = "$year.$build.0.$Env:APPVEYOR_BUILD_NUMBER"

    Write-Host $version

    Update-AppveyorBuild -Version $version

before_build:
- ps: >-
    $Env:APPVEYOR_BUILD_VERSION -match "(\d+)\.(\d+)\.(\d+)\.(\d+)"

    $m = $matches

    $file = gci "$Env:APPVEYOR_BUILD_FOLDER\res\bldver.rc"

    if($file)

    {
     attrib $file -r
     $fc = Get-Content($file)
     $fc = $fc -replace "#define rmj (\d+)", ("#define rmj "+$m[1])
     $fc = $fc -replace "#define rmm (\d+)", ("#define rmm "+$m[2])
     $fc = $fc -replace "#define rup (\d+)", ("#define rup "+$m[3])
     $fc = $fc -replace "#define rmn (\d+)", ("#define rmn "+$m[4])
     $fc | Out-File $file
    }

build:
  project: MFCMAPI.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: >-
    . ($Env:APPVEYOR_BUILD_FOLDER + '\Deploy\Compress-File.ps1')


    $indir = "$Env:APPVEYOR_BUILD_FOLDER\bin"

    $outdir = "$Env:APPVEYOR_BUILD_FOLDER\archives"

    $version = $Env:APPVEYOR_BUILD_VERSION


    if (!(Test-Path $outdir)) {New-Item -Path $outdir -Type Directory}


    Compress-File -Source "$indir\Win32\MrMAPI\Release\MrMAPI.exe" -Target "$outdir\MrMAPI.exe.$version.zip"

    Compress-File -Source "$indir\Win32\MrMAPI\Release\MrMAPI.pdb" -Target "$outdir\MrMAPI.pdb.$version.zip"

    Compress-File -Source "$indir\x64\MrMAPI\Release\MrMAPI.exe" -Target "$outdir\MrMAPI.exe.x64.$version.zip"

    Compress-File -Source "$indir\x64\MrMAPI\Release\MrMAPI.pdb" -Target "$outdir\MrMAPI.pdb.x64.$version.zip"

    Compress-File -Source "$indir\Win32\Release\MFCMAPI.exe" -Target "$outdir\MFCMAPI.exe.$version.zip"

    Compress-File -Source "$indir\Win32\Release\MFCMAPI.pdb" -Target "$outdir\MFCMAPI.pdb.$version.zip"

    Compress-File -Source "$indir\x64\Release\MFCMAPI.exe" -Target "$outdir\MFCMAPI.exe.x64.$version.zip"

    Compress-File -Source "$indir\x64\Release\MFCMAPI.pdb" -Target "$outdir\MFCMAPI.pdb.x64.$version.zip"

test_script:
- cmd: vstest.console /logger:Appveyor %APPVEYOR_BUILD_FOLDER%\bin\%PLATFORM%\UnitTest\%CONFIGURATION%\UnitTest.dll

artifacts:
- path: Archives\MFCMAPI.exe.$(APPVEYOR_BUILD_VERSION).zip
  name: MFCMAPI 32 bit executable - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MFCMAPI.pdb.$(APPVEYOR_BUILD_VERSION).zip
  name: MFCMAPI 32 bit symbol - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MFCMAPI.exe.x64.$(APPVEYOR_BUILD_VERSION).zip
  name: MFCMAPI 64 bit executable - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MFCMAPI.pdb.x64.$(APPVEYOR_BUILD_VERSION).zip
  name: MFCMAPI 64 bit symbol - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MrMAPI.exe.$(APPVEYOR_BUILD_VERSION).zip
  name: MrMAPI 32 bit executable - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MrMAPI.pdb.$(APPVEYOR_BUILD_VERSION).zip
  name: MrMAPI 32 bit symbol - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MrMAPI.exe.x64.$(APPVEYOR_BUILD_VERSION).zip
  name: MrMAPI 64 bit executable - Continuous Integration ($(APPVEYOR_BUILD_VERSION))
- path: Archives\MrMAPI.pdb.x64.$(APPVEYOR_BUILD_VERSION).zip
  name: MrMAPI 64 bit symbol - Continuous Integration ($(APPVEYOR_BUILD_VERSION))

deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  release: Continous Integration ($(APPVEYOR_BUILD_VERSION))
  description: "Build: *$(APPVEYOR_BUILD_VERSION)*\n\nThis is the continuous integration build of MFCMAPI.\n\nIf you just want to run the MFCMAPI or MrMAPI, get the executables. If you want to debug them, get the symbol files and the [source](https://github.com/stephenegriffin/mfcmapi).\n\n*The 64 bit builds will only work on a machine with Outlook 2010/2013/2016 64 bit installed. All other machines should use the 32 bit builds, regardless of the operating system.*\n\n[![Facebook Badge](http://badge.facebook.com/badge/26764016480.2776.1538253884.png)](http://www.facebook.com/MFCMAPI)\n\n[Download stats](https://www.somsubhra.com/github-release-stats/?username=stephenegriffin&repository=mfcmapi&search=0)"

  auth_token:
    secure: vJsUDJyfK/dEUbimHuxnA5id48OJR5UeHpB2WK8rcN7SslRJ08BHy9ecKctDJzx/
  artifact: /.*\.zip/
  draft: true